"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Students_1 = require("./Students");
var Teachers_1 = require("./Teachers");
var Course_1 = require("./Course");
var teacher1 = new Teachers_1.Teachers(1, 'MD Alamin');
var teacher2 = new Teachers_1.Teachers(2, 'Most Anika');
var student1 = new Students_1.default(1, 'Rayhan');
var student2 = new Students_1.default(2, 'Abdullah');
var course1 = new Course_1.default(1, 'WebTech', teacher1);
course1.addStudent(student1);
course1.addStudent(student2);
var course2 = new Course_1.default(2, 'OS', teacher2);
course2.addStudent(student1);
teacher1.addCourse(course1.courseName);
teacher2.addCourse(course2.courseName);
student1.enrollCourse(course1.courseName);
student1.enrollCourse(course2.courseName);
student2.enrollCourse(course2.courseName);
console.log(student1.toString());
student1.showCourses();
console.log(teacher1.toString());
teacher1.showCourses();
console.log(teacher2.toString());
teacher2.showCourses();
course1.showStudents();
course2.showStudents();
